name: Verify Addon

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BLENDER_VERSION: blender-4.2.0-beta+v42.d19d23e91f65-linux.x86_64-release
    steps:
      - name: Set derived environment variables
        run: |
          echo "BLENDER_FILENAME=${{ env.BLENDER_VERSION }}.tar.xz" >> $GITHUB_ENV
          echo "BLENDER_URL=https://cdn.builder.blender.org/download/daily/${{ env.BLENDER_VERSION }}.tar.xz" >> $GITHUB_ENV
      - name: Install Blender Dependencies
        run: |
          sudo apt-get install libxxf86vm-dev -y
          sudo apt-get install libxfixes3 -y
          sudo apt-get install libxi-dev -y
          sudo apt-get install libxkbcommon-x11-0 -y
          sudo apt-get install libgl1-mesa-glx -y
      - name: Download & Extract Blender
        run: |
          wget -q $BLENDER_URL
          tar -xf $BLENDER_FILENAME
          rm -rf $BLENDER_FILENAME
      - name: Add Blender executable to path
        run: |
          echo "${{ github.workspace }}/${{ env.BLENDER_VERSION }}/" >> $GITHUB_PATH
      - name: Sanity check that Blender is on the path
        run: |
          blender --version
      - uses: actions/checkout@v3
      - name: Build addon
        run: |
          pushd ./io_scene_psk_psa
          ls -lf
          echo $GITHUB_PATH
          blender --command extension build
          popd
      - name: Archive addon
        uses: actions/upload-artifact@v4
        with:
          name: addon
          path: |
            ./io_scene_psk_psa/io_scene_psk_psa.zip
