name: Verify Addon

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BLENDER_VERSION: blender-4.2.0-beta+v42.d19d23e91f65-linux.x86_64-release
    steps:
      - name: Set derived environment variables
        run: |
          echo "BLENDER_FILENAME=${{ env.BLENDER_VERSION }}.tar.xz" >> $GITHUB_ENV
          echo "BLENDER_URL=https://cdn.builder.blender.org/download/daily/${{ env.BLENDER_VERSION }}.tar.xz" >> $GITHUB_ENV
      - name: Install Blender Dependencies
        run: |
          sudo apt-get install libxxf86vm-dev -y
          sudo apt-get install libxfixes3 -y
          sudo apt-get install libxi-dev -y
          sudo apt-get install libxkbcommon-x11-0 -y
          sudo apt-get install libgl1-mesa-glx -y
      - name: Download Blender
        run: |
          wget $BLENDER_URL
          ls
          tar -xf $BLENDER_FILENAME
          rm -rf $BLENDER_FILENAME
          ls
          ./${{ env.BLENDER_VERSION }}/blender --version
      - uses: actions/checkout@v3
