name: Verify Addon

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BLENDER_VERSION: blender-4.2.0-beta+v42.d19d23e91f65-linux.x86_64-release
  BLENDER_FILENAME: $BLENDER_VERSION.tar.xz
  BLENDER_URL: https://cdn.builder.blender.org/download/daily/$BLENDER_FILENAME
    
jobs:
  configurator:
    runs-on: ubuntu-latest
    steps:
    - name: Install Blender Dependencies
      run: |
        apt install libxxf86vm-dev -y
        apt install libxfixes3 -y
        apt install libxi-dev -y
        apt install libxkbcommon-x11-0 -y
        apt install libgl1-mesa-glx -y
    - name: Download Blender
      run: |
        wget ${{ env.BLENDER_URL }}
        tar -xvzf ${{ env.BLENDER_FILENAME }}
        rm -rf ${{ env.BLENDER_FILENAME }}
    - uses: actions/checkout@v3
